### ISSUE TITLE
Makefile: build & build-mainnet targets are identical (?)

### ISSUE THREAD

**Issue by sbellem** [scrtlabs/secret-vrf-challenge-contract#1]
Perhaps I am missing something, but what is the difference between `make build` and `make build-mainnet`? 

https://github.com/scrtlabs/secret-vrf-challenge-contract/blob/353b378ecf601274d12525363516258fc319dd2b/Makefile#L1-L6

https://github.com/scrtlabs/secret-vrf-challenge-contract/blob/353b378ecf601274d12525363516258fc319dd2b/Makefile#L23-L29

**Comment by Cashmaney** [comment]
Hey, 

I don't think you're missing anything, it's just that it wasn't that important to differentiate between the two. For the most part it's a hacky simple contract, so that file was probably copy-pasted from somewhere and not looked at too deeply. Sometimes contracts like to have a different test/debug setup than mainnet, but for smaller scope I prefer defaulting to production compilation

**Comment by sbellem** [comment]
Thanks!
